server:
  port: 80 # 服务绑定的端口，不写默认是8080
  servlet:
    context-path: /thesis # 服务的路径，不写默认为空
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/thesis?serverTimezone=UTC #配置url地址 加上Serxxx防止报错
    username: root
    password: 123456
mybatis:
  typeAliasesPackage: com.jxufe.ljw.thesis.bean #实体类所在路径
  mapperLocations: xml/*.xml #mapper文件映射路径