server:
  port: 80 # 服务绑定的端口，不写默认是8080
  servlet:
    context-path: /thesis # 服务的路径，不写默认为空
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
  typeAliasesPackage: com.jxufe.ljw.thesis.bean #实体类所在路径
  mapperLocations: xml/*.xml #mapper文件映射路径
spring:
  mail:
    host: smtp.163.com #发送邮件服务器
    username: lejunwenme@163.com #发送邮件的邮箱地址
    password: Ab894436 #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    from: lejunwenme@163.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rjxy_thesis?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8 #配置url地址 加上Serxxx防止报错
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置获取连接等待超时的时间
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  servlet:
    multipart:
      max-request-size: 30MB
      enabled: true
      max-file-size: 30MB